export const nav = [{href:'/',label:'Home'},{href:'/about',label:'About'},{href:'/research',label:'Research'},{href:'/projects',label:'Projects'},{href:'/publications',label:'Publications'},{href:'/fieldwork',label:'Field Work'},{href:'/blog',label:'Blog'},{href:'/contact',label:'Contact'},{href:'/cv',label:'CV'}];
export type Project = { slug:string; title:string; short:string; description:string; technologies:string[]; paper?:string; github?:string; figure?:string; status:string };
export const projects: Project[] = [
 {slug:'gravity-inversion-julia', title:'Backend-agnostic Julia framework for 3D gravity inversion', short:'A high-performance framework for large-scale density-contrast inversion.', description:'A Julia-based framework using iterative conjugate-gradient solvers for three-dimensional gravity inversion on synthetic and real datasets.', technologies:['Julia','Inversion','HPC','PCG'], paper:'https://arxiv.org/abs/2602.03857', figure:'/images/julia-gravity-inversion-workflow.png', status:'Research software'},
 {slug:'basement-depth', title:'Basement depth estimation from gravity data using Physics-Guided Neural Networks and its comparison with data-driven deep learning', short:'Published work on physics-guided and data-driven learning for gravity inversion.', description:"A comparative framework for basement-depth estimation that integrates Poisson's equation within a physics-constrained loss and compares the resulting PGNN with a data-driven CNN.", technologies:['Python','TensorFlow','PGNN','CNN'], paper:'https://doi.org/10.1016/j.cageo.2026.106200', github:'https://github.com/naimat04/PGNN-Basement-Depth-Estimation', figure:'/images/basement-depth-pgnn.jpg', status:'Published · 2026'},
 {slug:'tem-inversion', title:'TEM inversion using deep learning', short:'Data-driven conductivity estimation from transient electromagnetic data.', description:'A deep-learning workflow for estimating subsurface conductivity models from observed TEM data using synthetic forward simulations.', technologies:['Python','Deep Learning','TEM','SciPy'], figure:'/images/tem_5.png', status:'Research project'},
 {slug:'magnetic-inversion', title:'Physics-Guided Deep Learning for Enhanced 2-D Magnetic Inversion of Multi-Source Susceptibility Structures', short:'Physics-guided magnetic inversion under remanent-magnetization uncertainty.', description:'A physics-guided deep-learning approach to two-dimensional magnetic inversion that addresses remanent magnetization and unknown magnetization direction in multi-source susceptibility structures.', technologies:['Python','PyTorch','U-Net','Magnetic inversion'], figure:'/images/Figure5.png', status:'Under review'}
] ;
export type Publication = { title:string; authors:string; venue:string; year:string; status:string; url?:string; linkLabel?:string; abstract:string };
export const publications: Publication[] = [
 {title:'Basement depth estimation from gravity data using Physics-Guided Neural Networks and its comparison with data-driven deep learning', authors:'Kuldeep Sarkar, Nimatullah, Anand Singh, and Upendra K. Singh', venue:'Computers & Geosciences, 214, 106200', year:'2026', status:'Published', url:'https://doi.org/10.1016/j.cageo.2026.106200', linkLabel:'DOI', abstract:"A Physics-Guided Neural Network using a modified Xception encoder–decoder and a physics-constrained loss for basement-depth estimation from gravity anomalies, compared with a data-driven CNN."},
 {title:'High-performance 3D gravity inversion in Julia', authors:'Nimatullah', venue:'Under review', year:'2026–present', status:'Under review', url:'https://arxiv.org/abs/2602.03857', linkLabel:'Preprint', abstract:'A Julia-based framework for three-dimensional density-contrast inversion with iterative solvers and regularization.'},
 {title:'Physics-Guided Deep Learning for Enhanced 2-D Magnetic Inversion of Multi-Source Susceptibility Structures', authors:'Nimatullah', venue:'Under review', year:'2026–present', status:'Under review', abstract:'A physics-guided deep-learning approach to two-dimensional magnetic inversion for multi-source susceptibility structures.'}
] ;
export type Fieldwork = { name:string; code:string; text:string; images:string[] };
export const fieldwork: Fieldwork[] = [
 {name:'Transient electromagnetic surveys', code:'TEM', text:'Groundwater exploration and depth sounding using transmitter loops and receiver coils to characterize conductivity variations after current cutoff.', images:['/images/tem_1.jpeg','/images/tem_2.jpeg','/images/tem_3.png']},
 {name:'DC resistivity & cross-well ERT', code:'DC / ERT', text:'Vertical electrical sounding and two-dimensional imaging with Wenner and Schlumberger arrays for aquifer characterization.', images:['/images/dc_1.jpeg','/images/cross_well_1.jpeg','/images/cross_well_2.jpeg']},
 {name:'Very low frequency EM', code:'VLF', text:'Tilt-angle and ellipticity measurements for mapping shallow conductors and geological faults.', images:['/images/vlf_1.jpeg','/images/vlf_2.jpeg','/images/vlf_magnetic_11.jpeg']},
 {name:'Ground magnetic surveys', code:'MAG', text:'Total magnetic intensity acquisition using proton-precession and fluxgate magnetometers for anomaly mapping and inversion.', images:['/images/magnetic_field.jpeg','/images/geological_field.jpeg']}
] ;
